/**
 * Exercise library seed data (§8.1).
 *
 * This file is the source of truth; `npm run seed:exercises` pushes it to the
 * `exercises` table. Ids are assigned here and never reused, because
 * `progression_of` and `workout_sets.exercise_id` reference them.
 *
 * Progression chains follow §8.1: push-up → diamond → archer → pseudo-planche;
 * dead hang → scap pull → negative → band-assisted → pull-up → weighted; squat →
 * split squat → Bulgarian → pistol. Ab chains follow §8.2.
 */

export const MUSCLE_GROUPS = [
  'chest',
  'back',
  'shoulders',
  'arms',
  'legs',
  'core',
  'full_body',
  'neck',
  'mobility',
] as const;

export type MuscleGroup = (typeof MUSCLE_GROUPS)[number];

export const EQUIPMENT = [
  'bodyweight',
  'pull_up_bar',
  'dumbbells',
  'barbell',
  'bench',
  'machines',
  'bands',
] as const;

export type Equipment = (typeof EQUIPMENT)[number];

export type Level = 'beginner' | 'intermediate' | 'advanced';

export interface ExerciseSeed {
  id: number;
  slug: string;
  name: string;
  muscle_group: MuscleGroup;
  equipment: Equipment;
  level: Level;
  is_bodyweight: boolean;
  cues: string[];
  mistakes: string[];
  /** Slug of the exercise this one progresses from. */
  progression_of?: string;
}

export const EXERCISES: ExerciseSeed[] = [
  // -------------------------------------------------------------------------
  // chest
  // -------------------------------------------------------------------------
  {
    id: 1,
    slug: 'incline_push_up',
    name: 'Incline push-up',
    muscle_group: 'chest',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Hands on a bench or table', 'Body in one line from heel to head', 'Chest to the surface'],
    mistakes: ['Hips sagging', 'Head dropping before the chest'],
  },
  {
    id: 2,
    slug: 'knee_push_up',
    name: 'Knee push-up',
    muscle_group: 'chest',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Knees, hips and shoulders in one line', 'Elbows about 45 degrees from the body'],
    mistakes: ['Hips piking up', 'Half range of motion'],
    progression_of: 'incline_push_up',
  },
  {
    id: 3,
    slug: 'push_up',
    name: 'Push-up',
    muscle_group: 'chest',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Squeeze glutes and brace', 'Elbows 45 degrees, not flared', 'Chest to the floor'],
    mistakes: ['Sagging hips', 'Flaring elbows to 90 degrees', 'Bouncing off the floor'],
    progression_of: 'knee_push_up',
  },
  {
    id: 4,
    slug: 'diamond_push_up',
    name: 'Diamond push-up',
    muscle_group: 'chest',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Index fingers and thumbs together', 'Elbows brush past the ribs'],
    mistakes: ['Elbows flaring wide', 'Shortening the range to keep reps up'],
    progression_of: 'push_up',
  },
  {
    id: 5,
    slug: 'archer_push_up',
    name: 'Archer push-up',
    muscle_group: 'chest',
    equipment: 'bodyweight',
    level: 'advanced',
    is_bodyweight: true,
    cues: ['Wide hands', 'Bend one arm, keep the other straight', 'Alternate sides each rep'],
    mistakes: ['Rotating the hips to cheat', 'Letting the straight arm bend'],
    progression_of: 'diamond_push_up',
  },
  {
    id: 6,
    slug: 'pseudo_planche_push_up',
    name: 'Pseudo-planche push-up',
    muscle_group: 'chest',
    equipment: 'bodyweight',
    level: 'advanced',
    is_bodyweight: true,
    cues: ['Hands by the waist, fingers turned out', 'Lean forward so shoulders pass the hands'],
    mistakes: ['Not leaning far enough to load the shoulders', 'Flaring the elbows'],
    progression_of: 'archer_push_up',
  },
  {
    id: 7,
    slug: 'decline_push_up',
    name: 'Decline push-up',
    muscle_group: 'chest',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Feet raised on a bench', 'Keep the ribs down'],
    mistakes: ['Overarching the lower back', 'Feet so high it becomes a shoulder press'],
  },
  {
    id: 8,
    slug: 'bench_press',
    name: 'Barbell bench press',
    muscle_group: 'chest',
    equipment: 'barbell',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Shoulder blades pulled back and down', 'Bar to the lower chest', 'Drive feet into the floor'],
    mistakes: ['Bouncing the bar off the chest', 'Elbows flared to 90 degrees', 'Lifting the hips off the bench'],
  },
  {
    id: 9,
    slug: 'incline_bench_press',
    name: 'Incline bench press',
    muscle_group: 'chest',
    equipment: 'barbell',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Bench at 30 degrees', 'Bar to the upper chest'],
    mistakes: ['Bench set too steep, turning it into a shoulder press'],
  },
  {
    id: 10,
    slug: 'dumbbell_bench_press',
    name: 'Dumbbell bench press',
    muscle_group: 'chest',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Wrists stacked over elbows', 'Lower until the chest stretches'],
    mistakes: ['Clashing the dumbbells at the top', 'Cutting the range short'],
  },
  {
    id: 11,
    slug: 'dumbbell_fly',
    name: 'Dumbbell fly',
    muscle_group: 'chest',
    equipment: 'dumbbells',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Soft elbow bend, held throughout', 'Wide arc, stop at chest level'],
    mistakes: ['Going too heavy and turning it into a press', 'Dropping below a comfortable shoulder stretch'],
  },
  {
    id: 12,
    slug: 'machine_chest_press',
    name: 'Machine chest press',
    muscle_group: 'chest',
    equipment: 'machines',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Set the seat so handles line up with mid-chest', 'Controlled negative'],
    mistakes: ['Seat too high or too low', 'Letting the weight stack slam'],
  },
  {
    id: 13,
    slug: 'chest_dip',
    name: 'Chest dip',
    muscle_group: 'chest',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Lean the torso forward', 'Lower until the shoulders are level with the elbows'],
    mistakes: ['Dropping too deep and straining the shoulder', 'Shrugging at the bottom'],
  },

  // -------------------------------------------------------------------------
  // back
  // -------------------------------------------------------------------------
  {
    id: 14,
    slug: 'dead_hang',
    name: 'Dead hang',
    muscle_group: 'back',
    equipment: 'pull_up_bar',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Full grip, thumbs around the bar', 'Relax and breathe', 'Build to 45 seconds'],
    mistakes: ['Gripping with a half grip', 'Holding the breath'],
  },
  {
    id: 15,
    slug: 'scap_pull_up',
    name: 'Scapular pull-up',
    muscle_group: 'back',
    equipment: 'pull_up_bar',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Arms stay straight', 'Pull the shoulders down away from the ears', 'Small range, big intent'],
    mistakes: ['Bending the elbows', 'Rushing the reps'],
    progression_of: 'dead_hang',
  },
  {
    id: 16,
    slug: 'negative_pull_up',
    name: 'Negative pull-up',
    muscle_group: 'back',
    equipment: 'pull_up_bar',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Jump to the top position', 'Lower for 3 to 5 seconds', 'Keep tension to the bottom'],
    mistakes: ['Dropping instead of lowering', 'Skipping the last part of the range'],
    progression_of: 'scap_pull_up',
  },
  {
    id: 17,
    slug: 'band_assisted_pull_up',
    name: 'Band-assisted pull-up',
    muscle_group: 'back',
    equipment: 'bands',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Foot or knee in the band', 'Chest to the bar', 'Drop to a lighter band as reps climb'],
    mistakes: ['Band so thick the lats barely work', 'Kipping off the band tension'],
    progression_of: 'negative_pull_up',
  },
  {
    id: 18,
    slug: 'pull_up',
    name: 'Pull-up',
    muscle_group: 'back',
    equipment: 'pull_up_bar',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Start from a dead hang', 'Drive the elbows down to the ribs', 'Chin clearly over the bar'],
    mistakes: ['Kipping', 'Half reps from the top', 'Shrugging instead of pulling with the lats'],
    progression_of: 'band_assisted_pull_up',
  },
  {
    id: 19,
    slug: 'weighted_pull_up',
    name: 'Weighted pull-up',
    muscle_group: 'back',
    equipment: 'pull_up_bar',
    level: 'advanced',
    is_bodyweight: false,
    cues: ['Add weight only once 8 clean reps are easy', 'Belt or dumbbell between the feet'],
    mistakes: ['Adding weight before the form is solid', 'Cutting the range as load goes up'],
    progression_of: 'pull_up',
  },
  {
    id: 20,
    slug: 'chin_up',
    name: 'Chin-up',
    muscle_group: 'back',
    equipment: 'pull_up_bar',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Palms facing you, shoulder width', 'Chest to the bar'],
    mistakes: ['Swinging', 'Elbows drifting forward'],
  },
  {
    id: 21,
    slug: 'inverted_row',
    name: 'Inverted row',
    muscle_group: 'back',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Body straight, heels on the floor', 'Pull the chest to the bar', 'Squeeze the shoulder blades'],
    mistakes: ['Hips sagging', 'Pulling with the arms and not the back'],
  },
  {
    id: 22,
    slug: 'barbell_row',
    name: 'Barbell row',
    muscle_group: 'back',
    equipment: 'barbell',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Hinge to about 45 degrees', 'Bar to the belly button', 'Flat back throughout'],
    mistakes: ['Rounding the lower back', 'Using the hips to heave the bar'],
  },
  {
    id: 23,
    slug: 'dumbbell_row',
    name: 'Single-arm dumbbell row',
    muscle_group: 'back',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Brace the free hand on a bench', 'Pull the elbow past the ribs', 'Keep the shoulders level'],
    mistakes: ['Twisting the torso to move more weight', 'Shrugging at the top'],
  },
  {
    id: 24,
    slug: 'lat_pulldown',
    name: 'Lat pulldown',
    muscle_group: 'back',
    equipment: 'machines',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Chest tall, slight lean back', 'Bar to the collarbone'],
    mistakes: ['Pulling behind the neck', 'Leaning back so far it becomes a row'],
  },
  {
    id: 25,
    slug: 'seated_cable_row',
    name: 'Seated cable row',
    muscle_group: 'back',
    equipment: 'machines',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Tall chest', 'Pull to the navel', 'Control the stretch back out'],
    mistakes: ['Rocking the torso for momentum', 'Rounding the back at the stretch'],
  },
  {
    id: 26,
    slug: 'face_pull',
    name: 'Face pull',
    muscle_group: 'back',
    equipment: 'bands',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Pull to the forehead', 'Elbows high, hands finish beside the ears'],
    mistakes: ['Going too heavy and turning it into a row', 'Shrugging'],
  },
  {
    id: 27,
    slug: 'deadlift',
    name: 'Deadlift',
    muscle_group: 'back',
    equipment: 'barbell',
    level: 'advanced',
    is_bodyweight: false,
    cues: ['Bar over mid-foot', 'Take the slack out before you pull', 'Push the floor away, lock out tall'],
    mistakes: ['Rounding the lower back', 'Hips shooting up first', 'Jerking the bar off the floor'],
  },

  // -------------------------------------------------------------------------
  // legs
  // -------------------------------------------------------------------------
  {
    id: 28,
    slug: 'bodyweight_squat',
    name: 'Bodyweight squat',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Feet shoulder width, toes slightly out', 'Sit between the hips', 'Knees track over the toes'],
    mistakes: ['Heels lifting', 'Knees caving in', 'Cutting depth short'],
  },
  {
    id: 29,
    slug: 'split_squat',
    name: 'Split squat',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Long stance', 'Back knee to just above the floor', 'Weight through the front heel'],
    mistakes: ['Stance too short, jamming the front knee', 'Leaning too far forward'],
    progression_of: 'bodyweight_squat',
  },
  {
    id: 30,
    slug: 'bulgarian_split_squat',
    name: 'Bulgarian split squat',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Rear foot on a bench', 'Front shin near vertical at the bottom', 'Control the descent'],
    mistakes: ['Bench too high', 'Pushing off the back foot'],
    progression_of: 'split_squat',
  },
  {
    id: 31,
    slug: 'assisted_pistol_squat',
    name: 'Assisted pistol squat',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Hold a doorframe or strap', 'Use the hands only as much as needed', 'Free leg straight ahead'],
    mistakes: ['Pulling hard with the arms the whole way', 'Collapsing at the bottom'],
    progression_of: 'bulgarian_split_squat',
  },
  {
    id: 32,
    slug: 'pistol_squat',
    name: 'Pistol squat',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'advanced',
    is_bodyweight: true,
    cues: ['Free leg straight and off the floor', 'Squat to full depth under control', 'Arms forward for balance'],
    mistakes: ['Heel lifting', 'Dropping into the bottom instead of lowering'],
    progression_of: 'assisted_pistol_squat',
  },
  {
    id: 33,
    slug: 'back_squat',
    name: 'Back squat',
    muscle_group: 'legs',
    equipment: 'barbell',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Bar on the upper back, not the neck', 'Brace before you descend', 'Hips and chest rise together'],
    mistakes: ['Knees caving', 'Chest dropping out of the hole', 'Heels rising'],
  },
  {
    id: 34,
    slug: 'front_squat',
    name: 'Front squat',
    muscle_group: 'legs',
    equipment: 'barbell',
    level: 'advanced',
    is_bodyweight: false,
    cues: ['Elbows high throughout', 'Bar rests on the shoulders, not the hands', 'Stay upright'],
    mistakes: ['Elbows dropping and the bar rolling forward', 'Rounding the upper back'],
  },
  {
    id: 35,
    slug: 'goblet_squat',
    name: 'Goblet squat',
    muscle_group: 'legs',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Hold a dumbbell at the chest', 'Elbows inside the knees at the bottom'],
    mistakes: ['Letting the weight pull the chest down', 'Partial depth'],
  },
  {
    id: 36,
    slug: 'romanian_deadlift',
    name: 'Romanian deadlift',
    muscle_group: 'legs',
    equipment: 'barbell',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Soft knees, hinge at the hips', 'Bar stays close to the legs', 'Stop when the hamstrings run out'],
    mistakes: ['Turning it into a squat', 'Rounding the back to chase depth'],
  },
  {
    id: 37,
    slug: 'hip_thrust',
    name: 'Hip thrust',
    muscle_group: 'legs',
    equipment: 'barbell',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Upper back on a bench', 'Chin tucked, ribs down', 'Squeeze the glutes at lockout'],
    mistakes: ['Overarching the lower back at the top', 'Pushing through the toes'],
  },
  {
    id: 38,
    slug: 'walking_lunge',
    name: 'Walking lunge',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Long steps', 'Torso tall', 'Drive through the front heel'],
    mistakes: ['Short steps that stress the knee', 'Front knee caving in'],
  },
  {
    id: 39,
    slug: 'leg_press',
    name: 'Leg press',
    muscle_group: 'legs',
    equipment: 'machines',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Feet mid-platform, shoulder width', 'Stop before the hips tuck under'],
    mistakes: ['Locking the knees hard at the top', 'Letting the lower back round'],
  },
  {
    id: 40,
    slug: 'leg_curl',
    name: 'Leg curl',
    muscle_group: 'legs',
    equipment: 'machines',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Hips stay down on the pad', 'Squeeze at the top, control the return'],
    mistakes: ['Lifting the hips to move more weight'],
  },
  {
    id: 41,
    slug: 'leg_extension',
    name: 'Leg extension',
    muscle_group: 'legs',
    equipment: 'machines',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Pad just above the ankles', 'Pause briefly at the top'],
    mistakes: ['Swinging the weight up', 'Going so heavy the knees feel it'],
  },
  {
    id: 42,
    slug: 'calf_raise',
    name: 'Standing calf raise',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Full stretch at the bottom', 'Pause at the top', 'Slow tempo'],
    mistakes: ['Bouncing through partial reps'],
  },
  {
    id: 43,
    slug: 'nordic_curl',
    name: 'Nordic hamstring curl',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'advanced',
    is_bodyweight: true,
    cues: ['Anchor the heels', 'Lower as slowly as you can', 'Catch with the hands'],
    mistakes: ['Bending at the hips', 'Dropping instead of resisting'],
  },
  {
    id: 44,
    slug: 'glute_bridge',
    name: 'Glute bridge',
    muscle_group: 'legs',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Heels close to the glutes', 'Drive the hips up, ribs down'],
    mistakes: ['Arching the lower back instead of squeezing the glutes'],
  },

  // -------------------------------------------------------------------------
  // shoulders
  // -------------------------------------------------------------------------
  {
    id: 45,
    slug: 'pike_push_up',
    name: 'Pike push-up',
    muscle_group: 'shoulders',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Hips high, body in an inverted V', 'Crown of the head to the floor'],
    mistakes: ['Hips dropping into a push-up', 'Elbows flaring wide'],
  },
  {
    id: 46,
    slug: 'elevated_pike_push_up',
    name: 'Elevated pike push-up',
    muscle_group: 'shoulders',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Feet on a chair or bench', 'Torso closer to vertical'],
    mistakes: ['Losing the vertical line', 'Rushing the negative'],
    progression_of: 'pike_push_up',
  },
  {
    id: 47,
    slug: 'wall_handstand_hold',
    name: 'Wall handstand hold',
    muscle_group: 'shoulders',
    equipment: 'bodyweight',
    level: 'advanced',
    is_bodyweight: true,
    cues: ['Chest to the wall if you can', 'Push the floor away', 'Ribs down, glutes squeezed'],
    mistakes: ['Banana back', 'Holding the breath'],
    progression_of: 'elevated_pike_push_up',
  },
  {
    id: 48,
    slug: 'overhead_press',
    name: 'Overhead press',
    muscle_group: 'shoulders',
    equipment: 'barbell',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Brace hard, glutes tight', 'Bar path close to the face', 'Finish with the bar over the ears'],
    mistakes: ['Leaning back excessively', 'Pressing around the head instead of past it'],
  },
  {
    id: 49,
    slug: 'dumbbell_shoulder_press',
    name: 'Dumbbell shoulder press',
    muscle_group: 'shoulders',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Start at ear height', 'Press slightly inward', 'Ribs down'],
    mistakes: ['Overarching the lower back', 'Clashing the dumbbells overhead'],
  },
  {
    id: 50,
    slug: 'lateral_raise',
    name: 'Lateral raise',
    muscle_group: 'shoulders',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Lead with the elbows', 'Stop at shoulder height', 'Light weight, strict form'],
    mistakes: ['Swinging the weight up', 'Shrugging the traps'],
  },
  {
    id: 51,
    slug: 'rear_delt_fly',
    name: 'Rear delt fly',
    muscle_group: 'shoulders',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Hinge forward', 'Arms sweep wide, not back', 'Squeeze behind the shoulders'],
    mistakes: ['Using the upper back to row the weight'],
  },
  {
    id: 52,
    slug: 'arnold_press',
    name: 'Arnold press',
    muscle_group: 'shoulders',
    equipment: 'dumbbells',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Start palms facing you', 'Rotate as you press'],
    mistakes: ['Rushing the rotation', 'Going too heavy for the shoulder position'],
  },
  {
    id: 53,
    slug: 'band_lateral_raise',
    name: 'Band lateral raise',
    muscle_group: 'shoulders',
    equipment: 'bands',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Stand on the band', 'Slow on the way down'],
    mistakes: ['Letting the band snap the arm back down'],
  },

  // -------------------------------------------------------------------------
  // arms
  // -------------------------------------------------------------------------
  {
    id: 54,
    slug: 'dumbbell_curl',
    name: 'Dumbbell curl',
    muscle_group: 'arms',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Elbows pinned to the sides', 'Full stretch at the bottom'],
    mistakes: ['Swinging the torso', 'Elbows drifting forward'],
  },
  {
    id: 55,
    slug: 'hammer_curl',
    name: 'Hammer curl',
    muscle_group: 'arms',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Neutral grip throughout', 'Control the negative'],
    mistakes: ['Rotating the wrist', 'Using the shoulders'],
  },
  {
    id: 56,
    slug: 'barbell_curl',
    name: 'Barbell curl',
    muscle_group: 'arms',
    equipment: 'barbell',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Shoulder-width grip', 'Elbows stay at the ribs'],
    mistakes: ['Leaning back to finish the rep'],
  },
  {
    id: 57,
    slug: 'band_curl',
    name: 'Band curl',
    muscle_group: 'arms',
    equipment: 'bands',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Stand on the band', 'Squeeze hard at the top where tension peaks'],
    mistakes: ['Letting the band pull the arm down fast'],
  },
  {
    id: 58,
    slug: 'bench_dip',
    name: 'Bench dip',
    muscle_group: 'arms',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Hands on the bench behind you', 'Elbows point straight back', 'Stop at 90 degrees'],
    mistakes: ['Dropping too low and straining the shoulders', 'Flaring the elbows'],
  },
  {
    id: 59,
    slug: 'parallel_bar_dip',
    name: 'Parallel bar dip',
    muscle_group: 'arms',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Torso upright for triceps', 'Lower to 90 degrees at the elbow'],
    mistakes: ['Dropping below 90 degrees and straining the shoulder', 'Bouncing out of the bottom'],
    progression_of: 'bench_dip',
  },
  {
    id: 60,
    slug: 'close_grip_bench_press',
    name: 'Close-grip bench press',
    muscle_group: 'arms',
    equipment: 'barbell',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Hands just inside shoulder width', 'Elbows tucked'],
    mistakes: ['Grip so narrow the wrists complain'],
  },
  {
    id: 61,
    slug: 'tricep_pushdown',
    name: 'Tricep pushdown',
    muscle_group: 'arms',
    equipment: 'machines',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Elbows locked at the sides', 'Full lockout, control back up'],
    mistakes: ['Leaning over the bar to press with bodyweight'],
  },
  {
    id: 62,
    slug: 'overhead_tricep_extension',
    name: 'Overhead tricep extension',
    muscle_group: 'arms',
    equipment: 'dumbbells',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Elbows point forward, close together', 'Full stretch behind the head'],
    mistakes: ['Elbows flaring wide', 'Arching the lower back'],
  },
  {
    id: 63,
    slug: 'skull_crusher',
    name: 'Skull crusher',
    muscle_group: 'arms',
    equipment: 'barbell',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Lower to the forehead or just behind', 'Upper arms stay still'],
    mistakes: ['Turning it into a close-grip press', 'Letting the elbows drift'],
  },

  // -------------------------------------------------------------------------
  // core — §8.2 chains
  // -------------------------------------------------------------------------
  {
    id: 64,
    slug: 'plank',
    name: 'Plank',
    muscle_group: 'core',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Elbows under shoulders', 'Ribs down, glutes squeezed', 'Quality over duration'],
    mistakes: ['Hips sagging or piking', 'Holding limp for time'],
  },
  {
    id: 65,
    slug: 'rkc_plank',
    name: 'RKC plank',
    muscle_group: 'core',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Pull the elbows toward the toes', 'Squeeze everything hard', '10 to 20 seconds is plenty'],
    mistakes: ['Treating it like a normal plank and holding for minutes'],
    progression_of: 'plank',
  },
  {
    id: 66,
    slug: 'ab_wheel_rollout',
    name: 'Ab wheel rollout',
    muscle_group: 'core',
    equipment: 'bodyweight',
    level: 'advanced',
    is_bodyweight: true,
    cues: ['Start from the knees', 'Ribs down the whole way', 'Only roll as far as you can hold the back flat'],
    mistakes: ['Lower back arching', 'Rolling out further than you can pull back'],
    progression_of: 'rkc_plank',
  },
  {
    id: 67,
    slug: 'hollow_hold',
    name: 'Hollow hold',
    muscle_group: 'core',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Lower back pressed into the floor', 'Shoulders and heels just off the ground'],
    mistakes: ['Lower back lifting away from the floor', 'Legs too low too soon'],
  },
  {
    id: 68,
    slug: 'hanging_knee_raise',
    name: 'Hanging knee raise',
    muscle_group: 'core',
    equipment: 'pull_up_bar',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Knees to the chest', 'Curl the pelvis up, do not just lift the legs'],
    mistakes: ['Swinging', 'Only hinging at the hip'],
    progression_of: 'hollow_hold',
  },
  {
    id: 69,
    slug: 'hanging_leg_raise',
    name: 'Hanging leg raise',
    muscle_group: 'core',
    equipment: 'pull_up_bar',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Legs straight to parallel or higher', 'Controlled on the way down'],
    mistakes: ['Using momentum from the last rep', 'Bending the knees to cheat'],
    progression_of: 'hanging_knee_raise',
  },
  {
    id: 70,
    slug: 'toes_to_bar',
    name: 'Toes to bar',
    muscle_group: 'core',
    equipment: 'pull_up_bar',
    level: 'advanced',
    is_bodyweight: true,
    cues: ['Toes touch the bar', 'Keep the legs as straight as you can'],
    mistakes: ['Kipping wildly', 'Losing control on the descent'],
    progression_of: 'hanging_leg_raise',
  },
  {
    id: 71,
    slug: 'cable_crunch',
    name: 'Cable crunch',
    muscle_group: 'core',
    equipment: 'machines',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Hips stay put, spine flexes', 'Crunch the ribs toward the pelvis'],
    mistakes: ['Turning it into a hip hinge', 'Pulling with the arms'],
  },
  {
    id: 72,
    slug: 'weighted_crunch',
    name: 'Weighted crunch',
    muscle_group: 'core',
    equipment: 'dumbbells',
    level: 'intermediate',
    is_bodyweight: false,
    cues: ['Hold the weight at the chest', 'Short range, hard squeeze'],
    mistakes: ['Yanking the neck forward'],
  },
  {
    id: 73,
    slug: 'side_plank',
    name: 'Side plank',
    muscle_group: 'core',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Elbow under the shoulder', 'Hips stacked and lifted'],
    mistakes: ['Hips dropping', 'Rotating forward'],
  },
  {
    id: 74,
    slug: 'dead_bug',
    name: 'Dead bug',
    muscle_group: 'core',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Lower back stays flat', 'Opposite arm and leg, slow'],
    mistakes: ['Back arching as the leg lowers', 'Rushing'],
  },
  {
    id: 75,
    slug: 'russian_twist',
    name: 'Russian twist',
    muscle_group: 'core',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Lean back, chest tall', 'Rotate from the ribs'],
    mistakes: ['Rounding the back', 'Swinging the arms only'],
  },
  {
    id: 76,
    slug: 'mountain_climber',
    name: 'Mountain climber',
    muscle_group: 'core',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Shoulders over the hands', 'Hips level, drive the knees in'],
    mistakes: ['Hips bouncing up and down'],
  },

  // -------------------------------------------------------------------------
  // full body / mobility — §8.1 counts Surya Namaskar as a warm-up block
  // -------------------------------------------------------------------------
  {
    id: 77,
    slug: 'surya_namaskar',
    name: 'Surya Namaskar',
    muscle_group: 'mobility',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Move with the breath', 'One round is both sides', 'Use it as the warm-up block'],
    mistakes: ['Rushing through the positions', 'Forcing depth in the backbend'],
  },
  {
    id: 78,
    slug: 'cat_cow',
    name: 'Cat-cow',
    muscle_group: 'mobility',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Move one vertebra at a time', 'Exhale to round, inhale to arch'],
    mistakes: ['Only moving the lower back'],
  },
  {
    id: 79,
    slug: 'worlds_greatest_stretch',
    name: "World's greatest stretch",
    muscle_group: 'mobility',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Deep lunge, elbow to the instep', 'Rotate and reach up'],
    mistakes: ['Letting the back knee collapse', 'Holding the breath'],
  },
  {
    id: 80,
    slug: 'band_pull_apart',
    name: 'Band pull-apart',
    muscle_group: 'mobility',
    equipment: 'bands',
    level: 'beginner',
    is_bodyweight: false,
    cues: ['Arms straight', 'Pull to the chest line', 'Squeeze the shoulder blades'],
    mistakes: ['Shrugging', 'Bending the elbows'],
  },
  {
    id: 81,
    slug: 'burpee',
    name: 'Burpee',
    muscle_group: 'full_body',
    equipment: 'bodyweight',
    level: 'intermediate',
    is_bodyweight: true,
    cues: ['Chest to the floor', 'Jump and land soft'],
    mistakes: ['Sagging hips on the push-up', 'Landing stiff-legged'],
  },

  // -------------------------------------------------------------------------
  // neck and posture — §8.4. Light, progressive, no jaw devices.
  // -------------------------------------------------------------------------
  {
    id: 82,
    slug: 'chin_tuck',
    name: 'Chin tuck',
    muscle_group: 'neck',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Draw the chin straight back, making a double chin', 'Hold 3 to 5 seconds', 'Eyes stay level'],
    mistakes: ['Tipping the head down instead of gliding it back', 'Forcing the range'],
  },
  {
    id: 83,
    slug: 'wall_angel',
    name: 'Wall angel',
    muscle_group: 'neck',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Lower back, upper back and head touch the wall', 'Slide the arms slowly'],
    mistakes: ['Lower back arching off the wall', 'Losing wall contact with the wrists'],
  },
  {
    id: 84,
    slug: 'neck_curl',
    name: 'Neck curl',
    muscle_group: 'neck',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Lie on your back, tuck the chin, lift the head slowly', 'Very light and controlled', 'Stop at any sharp feeling'],
    mistakes: ['Adding load too early', 'Jerking the head up'],
  },
  {
    id: 85,
    slug: 'neck_extension',
    name: 'Neck extension',
    muscle_group: 'neck',
    equipment: 'bodyweight',
    level: 'beginner',
    is_bodyweight: true,
    cues: ['Lie face down, lift the head slowly through a small range', 'Control both directions'],
    mistakes: ['Cranking the head back', 'Using momentum'],
  },
];

/** Resolves the progression chain into database rows. */
export function toDatabaseRows() {
  const idBySlug = new Map(EXERCISES.map((e) => [e.slug, e.id]));

  return EXERCISES.map((exercise) => ({
    id: exercise.id,
    slug: exercise.slug,
    name: exercise.name,
    muscle_group: exercise.muscle_group,
    equipment: exercise.equipment,
    level: exercise.level,
    is_bodyweight: exercise.is_bodyweight,
    cues: exercise.cues,
    mistakes: exercise.mistakes,
    progression_of: exercise.progression_of ? (idBySlug.get(exercise.progression_of) ?? null) : null,
    video_url: null,
  }));
}
